export const PASSWORD_ERROR = 'PASSWORD_ERROR'
export const DISABLE_PASSWORD_ERROR = 'DISABLE_PASSWORD_ERROR'

export const EMAIL_ERROR = 'EMAIL_ERROR'
export const DISABLE_EMAIL_ERROR = 'DISABLE_EMAIL_ERROR'

export const USERNAME_ERROR = 'USERNAME_ERROR'
export const DISABLE_USERNAME_ERROR = 'DISABLE_USERNAME_ERROR'

export const INVALID_USERNAME_PASSWORD_ERROR = 'INVALID_USERNAME_PASSWORD_ERROR'
export const DISABLE_INVALID_USERNAME_PASSWORD_ERROR = 'DISABLE_INVALID_USERNAME_PASSWORD_ERROR'

