export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_MYORDERS_REQUEST = 'ORDER_MYORDERS_REQUEST'
export const ORDER_MYORDERS_SUCCESS = 'ORDER_MYORDERS_SUCCESS'
export const ORDER_MYORDERS_FAIL = 'ORDER_MYORDERS_FAIL'