export const ENABLE_LOGIN_FORM = 'ENABLE_LOGIN_FORM'
export const DISABLE_LOGIN_FORM = 'DISABLE_LOGIN_FORM'
export const ENABLE_SIGNUP_FORM = 'ENABLE_SIGNUP_FORM'
export const DISABLE_SIGNUP_FORM = 'DISABLE_SIGNUP_FORM'
