export const Category = [
  'Men',
  'Women',
  'Boys',
  'Girls',
  'Infants',
]

export const Size = [
  'XS',
  'S',
  'M',
  'L',
  'XL',
  'XXL (2XL)',
  'XXXL (3XL)',
  'XXXL (4XL)',
  'VXL (5XL)',
  'Between 1 to 2 Years',
  'Between 2 to 3 Years',
  'Between 3 to 4 Years',
  'Between 4 to 5 Years',
  'Between 5 to 6 Years',
  'Between 6 to 7 Years',
  'Between 7 to 8 Years',
  'Between 8 to 9 Years',
  'Between 9 to 10 Years',
]

export const Color = [
  'Red',
  'Orange',
  'Yellow',
  'Chartreuse',
  'Green',
  'Spring green',
  'Cyan',
  'Azure',
  'Blue',
  'Violet',
  'Magenta',
  'Rose'
]

export const PickupTime = [
  'Between 9AM - 10AM',
  'Between 10AM - 11AM',
  'Between 11AM - 12PM',
  'Between 12PM - 1PM',
  'Between 1PM - 2PM',
  'Between 2PM - 3PM',
  'Between 3PM - 4PM',
  'Between 4PM - 5PM',
  'Between 5PM - 6PM',
  'Between 6PM - 7PM',  
]

export const colorsAdvanced = [
  { id: 'Absolute Zero', color: '#0048BA' },
  { id: 'Acid green', color: '#B0BF1A' },
  { id: 'Aero', color: '#7CB9E8' },
  { id: 'Aero blue', color: '#C0E8D5' },
  { id: 'African violet', color: '#B284BE' },
  { id: 'Air superiority blue', color: '#72A0C1' },
  { id: 'Alabaster', color: '#EDEAE0' },
  { id: 'Alice blue', color: '#F0F8FF' },
  { id: 'Alloy orange', color: '#C46210' },
  { id: 'Almond', color: '#EFDECD' },
  { id: 'Amaranth', color: '#E52B50' },
  { id: 'Amaranth (M&P)', color: '#9F2B68' },
  { id: 'Amaranth pink', color: '#F19CBB' },
  { id: 'Amaranth purple', color: '#AB274F' },
  { id: 'Amaranth red', color: '#D3212D' },
  { id: 'Amazon', color: '#3B7A57' },
  { id: 'Amber', color: '#FFBF00' },
  { id: 'Amber (SAE/ECE)', color: '#FF7E00' },
  { id: 'Amethyst', color: '#9966CC' },
  { id: 'Android green', color: '#3DDC84' },
  { id: 'Antique brass', color: '#CD9575' },
  { id: 'Antique bronze', color: '#665D1E' },
  { id: 'Antique fuchsia', color: '#915C83' },
  { id: 'Antique ruby', color: '#841B2D' },
  { id: 'Antique white', color: '#FAEBD7' },
  { id: 'Ao (English)', color: '#008000' },
  { id: 'Apple green', color: '#8DB600' },
  { id: 'Apricot', color: '#FBCEB1' },
  { id: 'Aqua', color: '#00FFFF' },
  { id: 'Aquamarine', color: '#7FFFD4' },
  { id: 'Arctic lime', color: '#D0FF14' },
  { id: 'Army green', color: '#4B5320' },
  { id: 'Artichoke', color: '#8F9779' },
  { id: 'Arylide yellow', color: '#E9D66B' },
  { id: 'Ash gray', color: '#B2BEB5' },
  { id: 'Asparagus', color: '#87A96B' },
  { id: 'Atomic tangerine', color: '#FF9966' },
  { id: 'Auburn', color: '#A52A2A' },
  { id: 'Aureolin', color: '#FDEE00' },
  { id: 'Avocado', color: '#568203' },
  { id: 'Azure', color: '#007FFF' },
  { id: 'Azure (X11/web color)', color: '#F0FFFF' },
  { id: 'Baby blue', color: '#89CFF0' },
  { id: 'Baby blue eyes', color: '#A1CAF1' },
  { id: 'Baby pink', color: '#F4C2C2' },
  { id: 'Baby powder', color: '#FEFEFA' },
  { id: 'Baker-Miller pink', color: '#FF91AF' },
  { id: 'Banana Mania', color: '#FAE7B5' },
  { id: 'Barbie Pink', color: '#DA1884' },
  { id: 'Barn red', color: '#7C0A02' },
  { id: 'Battleship grey', color: '#848482' },
  { id: 'Beau blue', color: '#BCD4E6' },
  { id: 'Beaver', color: '#9F8170' },
  { id: 'Beige', color: '#F5F5DC' },
  { id: 'B/\'dazzled blue', color: '#2E5894' },
  { id: 'Big dip o’ruby', color: '#9C2542' },
  { id: 'Bisque', color: '#FFE4C4' },
  { id: 'Bistre', color: '#3D2B1F' },
  { id: 'Bistre brown', color: '#967117' },
  { id: 'Bitter lemon', color: '#CAE00D' },
  { id: 'Bitter lime', color: '#BFFF00' },
  { id: 'Bittersweet', color: '#FE6F5E' },
  { id: 'Bittersweet shimmer', color: '#BF4F51' },
  { id: 'Black', color: '#000000' },
  { id: 'Black bean', color: '#3D0C02' },
  { id: 'Black chocolate', color: '#1B1811' },
  { id: 'Black coffee', color: '#3B2F2F' },
  { id: 'Black coral', color: '#54626F' },
  { id: 'Black olive', color: '#3B3C36' },
  { id: 'Black Shadows', color: '#BFAFB2' },
  { id: 'Blanched almond', color: '#FFEBCD' },
  { id: 'Blast-off bronze', color: '#A57164' },
  { id: 'Bleu de France', color: '#318CE7' },
  { id: 'Blizzard blue', color: '#ACE5EE' },
  { id: 'Blond', color: '#FAF0BE' },
  { id: 'Blood red', color: '#660000' },
  { id: 'Blue', color: '#0000FF' },
  { id: 'Blue (Crayola)', color: '#1F75FE' },
  { id: 'Blue (Munsell)', color: '#0093AF' },
  { id: 'Blue (NCS)', color: '#0087BD' },
  { id: 'Blue (Pantone)', color: '#0018A8' },
  { id: 'Blue (pigment)', color: '#333399' },
  { id: 'Blue (RYB)', color: '#0247FE' },
  { id: 'Blue bell', color: '#A2A2D0' },
  { id: 'Blue-gray', color: '#6699CC' },
  { id: 'Blue-green', color: '#0D98BA' },
  { id: 'Blue-green (color wheel)', color: '#064E40' },
  { id: 'Blue jeans', color: '#5DADEC' },
  { id: 'Blue sapphire', color: '#126180' },
  { id: 'Blue-violet', color: '#8A2BE2' },
  { id: 'Blue-violet (Crayola)', color: '#7366BD' },
  { id: 'Blue-violet (color wheel)', color: '#4D1A7F' },
  { id: 'Blue yonder', color: '#5072A7' },
  { id: 'Bluetiful', color: '#3C69E7' },
  { id: 'Blush', color: '#DE5D83' },
  { id: 'Bole', color: '#79443B' },
  { id: 'Bone', color: '#E3DAC9' },
  { id: 'Bottle green', color: '#006A4E' },
  { id: 'Brandy', color: '#87413F' },
  { id: 'Brick red', color: '#CB4154' },
  { id: 'Bright green', color: '#66FF00' },
  { id: 'Bright lilac', color: '#D891EF' },
  { id: 'Bright maroon', color: '#C32148' },
  { id: 'Bright navy blue', color: '#1974D2' },
  { id: 'Bright yellow (Crayola)', color: '#FFAA1D' },
  { id: 'Brilliant rose', color: '#FF55A3' },
  { id: 'Brink pink', color: '#FB607F' },
  { id: 'British racing green', color: '#004225' },
  { id: 'Bronze', color: '#CD7F32' },
  { id: 'Brown', color: '#88540B' },
  { id: 'Brown sugar', color: '#AF6E4D' },
  { id: 'Brunswick green', color: '#1B4D3E' },
  { id: 'Bud green', color: '#7BB661' },
  { id: 'Buff', color: '#FFC680' },
  { id: 'Burgundy', color: '#800020' },
  { id: 'Burlywood', color: '#DEB887' },
  { id: 'Burnished brown', color: '#A17A74' },
  { id: 'Burnt orange', color: '#CC5500' },
  { id: 'Burnt sienna', color: '#E97451' },
  { id: 'Burnt umber', color: '#8A3324' },
  { id: 'Byzantine', color: '#BD33A4' },
  { id: 'Byzantium', color: '#702963' },
  { id: 'Cadet', color: '#536872' },
  { id: 'Cadet blue', color: '#5F9EA0' },
  { id: 'Cadet blue (Crayola)', color: '#A9B2C3' },
  { id: 'Cadet grey', color: '#91A3B0' },
  { id: 'Cadmium green', color: '#006B3C' },
  { id: 'Cadmium orange', color: '#ED872D' },
  { id: 'Cadmium red', color: '#E30022' },
  { id: 'Cadmium yellow', color: '#FFF600' },
  { id: 'Café au lait', color: '#A67B5B' },
  { id: 'Café noir', color: '#4B3621' },
  { id: 'Cambridge blue', color: '#A3C1AD' },
  { id: 'Camel', color: '#C19A6B' },
  { id: 'Cameo pink', color: '#EFBBCC' },
  { id: 'Canary', color: '#FFFF99' },
  { id: 'Canary yellow', color: '#FFEF00' },
  { id: 'Candy apple red', color: '#FF0800' },
  { id: 'Candy pink', color: '#E4717A' },
  { id: 'Capri', color: '#00BFFF' },
  { id: 'Caput mortuum', color: '#592720' },
  { id: 'Cardinal', color: '#C41E3A' },
  { id: 'Caribbean green', color: '#00CC99' },
  { id: 'Carmine', color: '#960018' },
  { id: 'Carmine (M&P)', color: '#D70040' },
  { id: 'Carnation pink', color: '#FFA6C9' },
  { id: 'Carnelian', color: '#B31B1B' },
  { id: 'Carolina blue', color: '#56A0D3' },
  { id: 'Carrot orange', color: '#ED9121' },
  { id: 'Castleton green', color: '#00563F' },
  { id: 'Catawba', color: '#703642' },
  { id: 'Cedar Chest', color: '#C95A49' },
  { id: 'Celadon', color: '#ACE1AF' },
  { id: 'Celadon blue', color: '#007BA7' },
  { id: 'Celadon green', color: '#2F847C' },
  { id: 'Celeste', color: '#B2FFFF' },
  { id: 'Celtic blue', color: '#246BCE' },
  { id: 'Cerise', color: '#DE3163' },
  { id: 'Cerulean', color: '#007BA7' },
  { id: 'Cerulean blue', color: '#2A52BE' },
  { id: 'Cerulean frost', color: '#6D9BC3' },
  { id: 'Cerulean (Crayola)', color: '#1DACD6' },
  { id: 'CG blue', color: '#007AA5' },
  { id: 'CG red', color: '#E03C31' },
  { id: 'Champagne', color: '#F7E7CE' },
  { id: 'Champagne pink', color: '#F1DDCF' },
  { id: 'Charcoal', color: '#36454F' },
  { id: 'Charleston green', color: '#232B2B' },
  { id: 'Charm pink', color: '#E68FAC' },
  { id: 'Chartreuse (traditional)', color: '#DFFF00' },
  { id: 'Chartreuse (web)', color: '#7FFF00' },
  { id: 'Cherry blossom pink', color: '#FFB7C5' },
  { id: 'Chestnut', color: '#954535' },
  { id: 'Chili red', color: '#E23D28' },
  { id: 'China pink', color: '#DE6FA1' },
  { id: 'China rose', color: '#A8516E' },
  { id: 'Chinese red', color: '#AA381E' },
  { id: 'Chinese violet', color: '#856088' },
  { id: 'Chinese yellow', color: '#FFB200' },
  { id: 'Chocolate (traditional)', color: '#7B3F00' },
  { id: 'Chocolate (web)', color: '#D2691E' },
  { id: 'Chocolate Cosmos', color: '#58111A' },
  { id: 'Chrome yellow', color: '#FFA700' },
  { id: 'Cinereous', color: '#98817B' },
  { id: 'Cinnabar', color: '#E34234' },
  { id: 'Cinnamon Satin', color: '#CD607E' },
  { id: 'Citrine', color: '#E4D00A' },
  { id: 'Citron', color: '#9FA91F' },
  { id: 'Claret', color: '#7F1734' },
  { id: 'Cobalt blue', color: '#0047AB' },
  { id: 'Cocoa brown', color: '#D2691E' },
  { id: 'Coffee', color: '#6F4E37' },
  { id: 'Columbia Blue', color: '#B9D9EB' },
  { id: 'Congo pink', color: '#F88379' },
  { id: 'Cool grey', color: '#8C92AC' },
  { id: 'Copper', color: '#B87333' },
  { id: 'Copper (Crayola)', color: '#DA8A67' },
  { id: 'Copper penny', color: '#AD6F69' },
  { id: 'Copper red', color: '#CB6D51' },
  { id: 'Copper rose', color: '#996666' },
  { id: 'Coquelicot', color: '#FF3800' },
  { id: 'Coral', color: '#FF7F50' },
  { id: 'Coral pink', color: '#F88379' },
  { id: 'Cordovan', color: '#893F45' },
  { id: 'Corn', color: '#FBEC5D' },
  { id: 'Cornell red', color: '#B31B1B' },
  { id: 'Cornflower blue', color: '#6495ED' },
  { id: 'Cornsilk', color: '#FFF8DC' },
  { id: 'Cosmic cobalt', color: '#2E2D88' },
  { id: 'Cosmic latte', color: '#FFF8E7' },
  { id: 'Coyote brown', color: '#81613C' },
  { id: 'Cotton candy', color: '#FFBCD9' },
  { id: 'Cream', color: '#FFFDD0' },
  { id: 'Crimson', color: '#DC143C' },
  { id: 'Crimson (UA)', color: '#9E1B32' },
  { id: 'Crystal', color: '#A7D8DE' },
  { id: 'Cultured', color: '#F5F5F5' },
  { id: 'Cyan', color: '#00FFFF' },
  { id: 'Cyan (process)', color: '#00B7EB' },
  { id: 'Cyber grape', color: '#58427C' },
  { id: 'Cyber yellow', color: '#FFD300' },
  { id: 'Cyclamen', color: '#F56FA1' },
  { id: 'Dark blue-gray', color: '#666699' },
  { id: 'Dark brown', color: '#654321' },
  { id: 'Dark byzantium', color: '#5D3954' },
  { id: 'Dark cornflower blue', color: '#26428B' },
  { id: 'Dark cyan', color: '#008B8B' },
  { id: 'Dark electric blue', color: '#536878' },
  { id: 'Dark goldenrod', color: '#B8860B' },
  { id: 'Dark green', color: '#013220' },
  { id: 'Dark green (X11)', color: '#006400' },
  { id: 'Dark jungle green', color: '#1A2421' },
  { id: 'Dark khaki', color: '#BDB76B' },
  { id: 'Dark lava', color: '#483C32' },
  { id: 'Dark liver', color: '#534B4F' },
  { id: 'Dark liver (horses)', color: '#543D37' },
  { id: 'Dark magenta', color: '#8B008B' },
  { id: 'Dark moss green', color: '#4A5D23' },
  { id: 'Dark olive green', color: '#556B2F' },
  { id: 'Dark orange', color: '#FF8C00' },
  { id: 'Dark orchid', color: '#9932CC' },
  { id: 'Dark pastel green', color: '#03C03C' },
  { id: 'Dark purple', color: '#301934' },
  { id: 'Dark red', color: '#8B0000' },
  { id: 'Dark salmon', color: '#E9967A' },
  { id: 'Dark sea green', color: '#8FBC8F' },
  { id: 'Dark sienna', color: '#3C1414' },
  { id: 'Dark sky blue', color: '#8CBED6' },
  { id: 'Dark slate blue', color: '#483D8B' },
  { id: 'Dark slate gray', color: '#2F4F4F' },
  { id: 'Dark spring green', color: '#177245' },
  { id: 'Dark turquoise', color: '#00CED1' },
  { id: 'Dark violet', color: '#9400D3' },
  { id: 'Dartmouth green', color: '#00703C' },
  { id: 'Davy/\'s grey', color: '#555555' },
  { id: 'Deep cerise', color: '#DA3287' },
  { id: 'Deep champagne', color: '#FAD6A5' },
  { id: 'Deep chestnut', color: '#B94E48' },
  { id: 'Deep jungle green', color: '#004B49' },
  { id: 'Deep pink', color: '#FF1493' },
  { id: 'Deep saffron', color: '#FF9933' },
  { id: 'Deep sky blue', color: '#00BFFF' },
  { id: 'Deep Space Sparkle', color: '#4A646C' },
  { id: 'Deep taupe', color: '#7E5E60' },
  { id: 'Denim', color: '#1560BD' },
  { id: 'Denim blue', color: '#2243B6' },
  { id: 'Desert', color: '#C19A6B' },
  { id: 'Desert sand', color: '#EDC9AF' },
  { id: 'Dim gray', color: '#696969' },
  { id: 'Dodger blue', color: '#1E90FF' },
  { id: 'Dogwood rose', color: '#D71868' },
  { id: 'Drab', color: '#967117' },
  { id: 'Duke blue', color: '#00009C' },
  { id: 'Dutch white', color: '#EFDFBB' },
  { id: 'Earth yellow', color: '#E1A95F' },
  { id: 'Ebony', color: '#555D50' },
  { id: 'Ecru', color: '#C2B280' },
  { id: 'Eerie black', color: '#1B1B1B' },
  { id: 'Eggplant', color: '#614051' },
  { id: 'Eggshell', color: '#F0EAD6' },
  { id: 'Egyptian blue', color: '#1034A6' },
  { id: 'Eigengrau', color: '#16161D' },
  { id: 'Electric blue', color: '#7DF9FF' },
  { id: 'Electric green', color: '#00FF00' },
  { id: 'Electric indigo', color: '#6F00FF' },
  { id: 'Electric lime', color: '#CCFF00' },
  { id: 'Electric purple', color: '#BF00FF' },
  { id: 'Electric violet', color: '#8F00FF' },
  { id: 'Emerald', color: '#50C878' },
  { id: 'Eminence', color: '#6C3082' },
  { id: 'English green', color: '#1B4D3E' },
  { id: 'English lavender', color: '#B48395' },
  { id: 'English red', color: '#AB4B52' },
  { id: 'English vermillion', color: '#CC474B' },
  { id: 'English violet', color: '#563C5C' },
  { id: 'Erin', color: '#00FF40' },
  { id: 'Eton blue', color: '#96C8A2' },
  { id: 'Fallow', color: '#C19A6B' },
  { id: 'Falu red', color: '#801818' },
  { id: 'Fandango', color: '#B53389' },
  { id: 'Fandango pink', color: '#DE5285' },
  { id: 'Fashion fuchsia', color: '#F400A1' },
  { id: 'Fawn', color: '#E5AA70' },
  { id: 'Feldgrau', color: '#4D5D53' },
  { id: 'Fern green', color: '#4F7942' },
  { id: 'Field drab', color: '#6C541E' },
  { id: 'Fiery rose', color: '#FF5470' },
  { id: 'Firebrick', color: '#B22222' },
  { id: 'Fire engine red', color: '#CE2029' },
  { id: 'Fire opal', color: '#E95C4B' },
  { id: 'Flame', color: '#E25822' },
  { id: 'Flax', color: '#EEDC82' },
  { id: 'Flirt', color: '#A2006D' },
  { id: 'Floral white', color: '#FFFAF0' },
  { id: 'Fluorescent blue', color: '#15F4EE' },
  { id: 'Forest green (Crayola)', color: '#5FA777' },
  { id: 'Forest green (traditional)', color: '#014421' },
  { id: 'Forest green (web)', color: '#228B22' },
  { id: 'French beige', color: '#A67B5B' },
  { id: 'French bistre', color: '#856D4D' },
  { id: 'French blue', color: '#0072BB' },
  { id: 'French fuchsia', color: '#FD3F92' },
  { id: 'French lilac', color: '#86608E' },
  { id: 'French lime', color: '#9EFD38' },
  { id: 'French mauve', color: '#D473D4' },
  { id: 'French pink', color: '#FD6C9E' },
  { id: 'French raspberry', color: '#C72C48' },
  { id: 'French rose', color: '#F64A8A' },
  { id: 'French sky blue', color: '#77B5FE' },
  { id: 'French violet', color: '#8806CE' },
  { id: 'Frostbite', color: '#E936A7' },
  { id: 'Fuchsia', color: '#FF00FF' },
  { id: 'Fuchsia (Crayola)', color: '#C154C1' },
  { id: 'Fuchsia purple', color: '#CC397B' },
  { id: 'Fuchsia rose', color: '#C74375' },
  { id: 'Fulvous', color: '#E48400' },
  { id: 'Fuzzy Wuzzy',color: '#87421F' }
]
